spring:
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus
      api-key: ${DASHSCOPE_API_KEY}$
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  application:
    name: agent
  profiles:
    active: local
server:
  servlet:
    context-path: /api
upload:
  path: tmp/document

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: 'com.hezhaohui.agent.controller'
knife4j:
  enable: true
  setting:
    language: zh_cn